[package]
name = "gradience-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
gradience-lib = { path = "../gradience-lib" }
shellexpand = "3.1.0"
clap-markdown = "0.1.4"
include_dir = "0.7.4"